# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/ubuntu/.devcontainer/base.Dockerfile

FROM chillerrobot/ros-noetic-moveit-panda:first

RUN echo "source ./catkin_ws/devel/setup.bash" >> ~/.bashrc

# install ros-noetic-effort-controllers 